name: Bug report
description: Report a reproducible authprobe behavior issue.
title: "bug: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Please include concrete reproduction data so maintainers can debug in one pass.
  - type: input
    id: version
    attributes:
      label: authprobe version
      description: Paste exact output from `authprobe --version`.
      placeholder: authprobe 0.x.y (...)
    validations:
      required: true
  - type: textarea
    id: command
    attributes:
      label: Command run
      description: Include the full command, flags, and environment assumptions.
      placeholder: authprobe scan https://example.com/mcp --trace-failure --bundle evidence.zip
    validations:
      required: true
  - type: input
    id: target
    attributes:
      label: Target URL
      description: Full URL or redacted/sanitized equivalent.
      placeholder: https://example.com/mcp
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: Evidence attachment
      description: Attach `--bundle evidence.zip` OR paste `--json -` output (redact secrets first).
      placeholder: Attached evidence.zip, or JSON output below.
    validations:
      required: true
  - type: dropdown
    id: no_redact
    attributes:
      label: Was `--no-redact` used?
      options:
        - "No"
        - "Yes"
        - "Not sure"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
